# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adc6f76d828d843171a0448678b595b5c20ca1eed0f7a0771ce961dcd1338d6dd66e7151694b797cbea46d2e28b243d01ea59c97c196df72f085f4f38e99d74f

test:
  secret_key_base: 78af9919ebc993b03aad79f1c24233a900864e7ce36ca0bfd04ad53dcd4925cf40eede5d128d5bd47d91c19fa3940e14f9bb3e961f8be01e4e70fe9bea5a949d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
